const products = [
  {
    _id: "1",
    name: "Cargo jeans",
    image: "/images/cargo.jpg",
    brand: "Denim",
    Category: "Mens Jeans",
    Price: 2000,
    countInStock: 3,
    rating: 0,
    numreviews: 0,
  },
  {
    _id: "2",
    name: "Mens Jacket",
    image: "/images/jackets.jpg",
    brand: "Polo",
    Category: "Mens Cloth",
    Price: 1500,
    countInStock: 20,
    rating: 4,
    numreviews: 8,
  },
  {
    _id: "3",
    name: "Mens Jeanss",
    image: "/images/menjeanss.jpg",
    brand: "Denim",
    Category: "Mens Cloth",
    Price: 1500,
    countInStock: 15,
    rating: 4.5,
    numreviews: 10,
  },
  {
    _id: "4",
    name: "Mens Shirt",
    image: "/images/shirts.jpg",
    brand: "Polo",
    Category: "Mens Cloth",
    Price: 1500,
    countInStock: 10,
    rating: 3.5,
    numreviews: 10,
  },
  {
    _id: "5",
    name: "Mens T-Shirt",
    image: "/images/tshirt.jpg",
    brand: "Polo",
    Category: "Mens Cloth",
    Price: 1500,
    countInStock: 10,
    rating: 3.5,
    numreviews: 10,
  },
  {
    _id: "6",
    name: "Mens Watch",
    image: "/images/menwatch.jpg",
    brand: "Polo",
    Category: "Mens Cloth",
    Price: 5000,
    countInStock: 10,
    rating: 5,
    numreviews: 10,
  },
  {
    _id: "7",
    name: "Mens Perfume",
    image: "/images/menperfume.jpg",
    brand: "Boss",
    Category: "Mens Perfume",
    Price: 3500,
    countInStock: 10,
    rating: 4.5,
    numreviews: 10,
  },
  {
    _id: "8",
    name: "Top",
    image: "/images/top.jpg",
    brand: "Khaadi",
    Category: "womens Cloth",
    Price: 2500,
    countInStock: 10,
    rating: 3.5,
    numreviews: 10,
  },
  {
    _id: "9",
    name: "Women Jeans",
    image: "/images/womenjeans.jpg",
    brand: "Denim",
    Category: "womens Cloth",
    Price: 3500,
    countInStock: 10,
    rating: 3.5,
    numreviews: 10,
  },
  {
    _id: "10",
    name: "J.",
    image: "/images/womenperfumes.jpg",
    brand: "J.",
    Category: "womens perfume",
    Price: 2500,
    countInStock: 10,
    rating: 3.5,
    numreviews: 10,
  },
];

export default products;
